### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/etc/sysctl.conf' on Manjaro

### ISSUE THREAD

**Issue by JustM0J0** [GitHackTools/TorghostNG#3]
I am trying to use this in Manjaro but I get this error after I run `sudo python torghostng.py -s`:

```
[+] Applying display language... Done
 _____               _               _   _   _  ____ 
|_   _|__  _ __ __ _| |__   ___  ___| |_| \ | |/ ___|
  | |/ _ \| '__/ _` | '_ \ / _ \/ __| __|  \| | |  _ 
  | | (_) | | | (_| | | | | (_) \__ \ |_| |\  | |_| |
  |_|\___/|_|  \__, |_| |_|\___/|___/\__|_| \_|\____|
               |___/
TorghostNG 1.3 - Make all your internet traffic anonymized through Tor proxy
Rewritten from TorGhost with Python 3

[+] Start connecting to Tor
Traceback (most recent call last):
  File "torghostng.py", line 474, in <module>
    start_connecting()
  File "torghostng.py", line 268, in start_connecting
    if DISABLE_IPv6 == open(Sysctl).read():
FileNotFoundError: [Errno 2] No such file or directory: '/etc/sysctl.conf'
```

**Comment by gitkern3l** [comment]
Run touch `/etc/sysctl.conf`

**Comment by JustM0J0** [comment]
Thank you

**Comment by gitkern3l** [comment]
Well you can give TorghostNG 1.7 a try. May be it can fix your problem (auto create `sysctl.conf`)
