### ISSUE TITLE
problem with installing on Arch

### ISSUE THREAD

**Issue by shaeinst** [GitHackTools/TorghostNG#4]
sudo python3 install.py

[+] Applying display language... Done
 _____               _               _   _   _  ____ 
|_   _|__  _ __ __ _| |__   ___  ___| |_| \ | |/ ___|
  | |/ _ \| '__/ _` | '_ \ / _ \/ __| __|  \| | |  _ 
  | | (_) | | | (_| | | | | (_) \__ \ |_| |\  | |_| |
  |_|\___/|_|  \__, |_| |_|\___/|___/\__|_| \_|\____|
               |___/
TorghostNG 1.4 - Make all your internet traffic anonymized through Tor proxy
Rewritten from TorGhost with Python 3
[i] tor is already installed
[i] macchanger is already installed
[i] privoxy is already installed
[i] pip3 is already installed
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: Skipping pyinstaller as it is not installed.
[i] PyInstaller is already installed
[+] Installing TorghostNG...
144 INFO: PyInstaller: 3.3.1
144 INFO: Python: 3.8.3
145 INFO: Platform: Linux-5.6.14-arch1-1-x86_64-with-glibc2.2.5
147 INFO: wrote /home/lazy/codeDNA/Apps/Live/secBrowse/TorghostNG/torghostng.spec
151 INFO: An exception occured when testing for UPX:
151 INFO:   ValueError("invalid literal for int() with base 10: '96-git-d7ba31cab8ce+'")
151 INFO: UPX is not available.
152 INFO: Extending PYTHONPATH with paths
['/home/lazy/codeDNA/Apps/Live/secBrowse/TorghostNG',
 '/home/lazy/codeDNA/Apps/Live/secBrowse/TorghostNG']
152 INFO: checking Analysis
159 INFO: checking PYZ
159 INFO: Building PYZ because out00-PYZ.toc is non existent
159 INFO: Building PYZ (ZlibArchive) /home/lazy/codeDNA/Apps/Live/secBrowse/TorghostNG/build/torghostng/out00-PYZ.pyz
Traceback (most recent call last):
  File "/home/lazy/codeDNA/confiFILES/appFrameWorkModule/python/venv/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/lazy/codeDNA/confiFILES/appFrameWorkModule/python/venv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/lazy/codeDNA/confiFILES/appFrameWorkModule/python/venv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/lazy/codeDNA/confiFILES/appFrameWorkModule/python/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/lazy/codeDNA/confiFILES/appFrameWorkModule/python/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "/home/lazy/codeDNA/confiFILES/appFrameWorkModule/python/venv/lib/python3.8/site-packages/PyInstaller/building/api.py", line 98, in __init__
    self.__postinit__()
  File "/home/lazy/codeDNA/confiFILES/appFrameWorkModule/python/venv/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/home/lazy/codeDNA/confiFILES/appFrameWorkModule/python/venv/lib/python3.8/site-packages/PyInstaller/building/api.py", line 128, in assemble
    self.code_dict = {
  File "/home/lazy/codeDNA/confiFILES/appFrameWorkModule/python/venv/lib/python3.8/site-packages/PyInstaller/building/api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "/home/lazy/codeDNA/confiFILES/appFrameWorkModule/python/venv/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 624, in strip_paths_in_code
    consts = tuple(
  File "/home/lazy/codeDNA/confiFILES/appFrameWorkModule/python/venv/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 625, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "/home/lazy/codeDNA/confiFILES/appFrameWorkModule/python/venv/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 632, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)
cp: cannot stat 'dist/torghostng': No such file or directory
chmod: cannot access '/usr/bin/torghostng': No such file or directory
[*] Done
[i] You can run TorghostNG with 'torghostng'
[i] If you have any questions, take a look at TorghostNG Tutorial Videos here: https://bit.ly/34TNglL
    You will love it, i think :D

**Comment by gitkern3l** [comment]
Probably, your `pyinstaller` is buggy. You can try to reinstall it:
`sudo pip3 uninstall pyinstaller; pip3 install pyinstaller`

Or you can bypass `install.py` and run `sudo python3 torghostng.py -h`

**Comment by gitkern3l** [comment]
Well you can give Torghost 1.7 a try. May be it can fix your problem (No more `pyinstaller`)
